#!/bin/bash

python reclass_raster.py rasters/ABCO_Ensemble_rcp45_1990.img start_class.cfg categorize/ABCO_Ensemble_rcp45_1990_classed.img
python reclass_raster.py rasters/ABCO_Ensemble_rcp45_2060.img end_class.cfg categorize/ABCO_Ensemble_rcp45_2060_classed.img
python reclass_raster.py rasters/ABCO_Ensemble_rcp85_1990.img start_class.cfg categorize/ABCO_Ensemble_rcp85_1990_classed.img
python reclass_raster.py rasters/ABCO_Ensemble_rcp85_2060.img end_class.cfg categorize/ABCO_Ensemble_rcp85_2060_classed.img

python reclass_raster.py rasters/ALRU2_Ensemble_rcp45_1990.img start_class.cfg categorize/ALRU2_Ensemble_rcp45_1990_classed.img
python reclass_raster.py rasters/ALRU2_Ensemble_rcp45_2060.img end_class.cfg categorize/ALRU2_Ensemble_rcp45_2060_classed.img
python reclass_raster.py rasters/ALRU2_Ensemble_rcp85_1990.img start_class.cfg categorize/ALRU2_Ensemble_rcp85_1990_classed.img
python reclass_raster.py rasters/ALRU2_Ensemble_rcp85_2060.img end_class.cfg categorize/ALRU2_Ensemble_rcp85_2060_classed.img

python reclass_raster.py rasters/PIPO_Ensemble_rcp45_1990.img start_class.cfg categorize/PIPO_Ensemble_rcp45_1990_classed.img
python reclass_raster.py rasters/PIPO_Ensemble_rcp45_2060.img end_class.cfg categorize/PIPO_Ensemble_rcp45_2060_classed.img
python reclass_raster.py rasters/PIPO_Ensemble_rcp85_1990.img start_class.cfg categorize/PIPO_Ensemble_rcp85_1990_classed.img
python reclass_raster.py rasters/PIPO_Ensemble_rcp85_2060.img end_class.cfg categorize/PIPO_Ensemble_rcp85_2060_classed.img

python reclass_raster.py rasters/PSME_Ensemble_rcp45_1990.img start_class.cfg categorize/PSME_Ensemble_rcp45_1990_classed.img
python reclass_raster.py rasters/PSME_Ensemble_rcp45_2060.img end_class.cfg categorize/PSME_Ensemble_rcp45_2060_classed.img
python reclass_raster.py rasters/PSME_Ensemble_rcp85_1990.img start_class.cfg categorize/PSME_Ensemble_rcp85_1990_classed.img
python reclass_raster.py rasters/PSME_Ensemble_rcp85_2060.img end_class.cfg categorize/PSME_Ensemble_rcp85_2060_classed.img

python reclass_raster.py rasters/TSHE_Ensemble_rcp45_1990.img start_class.cfg categorize/TSHE_Ensemble_rcp45_1990_classed.img
python reclass_raster.py rasters/TSHE_Ensemble_rcp45_2060.img end_class.cfg categorize/TSHE_Ensemble_rcp45_2060_classed.img
python reclass_raster.py rasters/TSHE_Ensemble_rcp85_1990.img start_class.cfg categorize/TSHE_Ensemble_rcp85_1990_classed.img
python reclass_raster.py rasters/TSHE_Ensemble_rcp85_2060.img end_class.cfg categorize/TSHE_Ensemble_rcp85_2060_classed.img