#!/bin/bash
#################################################################
# Usage:
#  fvs pn /path/to/data
#################################################################

# 1st Arg: variant abbreviation
VARIANT="$1"
EXE="/usr/local/apps/growth-yield-batch/fvsbin/FVS$VARIANT.exe"
if [[ -x "$EXE" ]]
then
    echo "Using $EXE..."
else
    echo "File '$EXE' is not executable or found"
    exit 1
fi
shift 

# 2nd Arg: path to data directory 
# TODO: must contain .tre, .sum, .key, .chp  and ***.fvs files
DATADIR="$1"
if [[ -d "$DATADIR" ]]
then
    echo "Using data dir $DATADIR ..."
else
    echo "'$DATADIR' not found; please specify DATADIR"
    exit 1
fi
shift

TEMPDIR=`mktemp -d`
cd $TEMPDIR
echo "Working in temp directory $(pwd)"

cp $DATADIR/* .

# process the *_original.key files and create offsets 10 offsets at 5 yr intervals
echo "Creating offsets in temp directory $(pwd)"
python /usr/local/apps/growth-yield-batch/scripts/preproc/CreateOffsets.py $TEMPDIR $TEMPDIR 10 5
mkdir -p alt_treelists

# TODO 
#PREFIX="A4_04"
for f in *.key
do
	filename=$(basename "$f")
	extension="${filename##*.}"
	PREFIX="${filename%.*}"
	if [[ "$PREFIX" != *_original* ]]
	then
		echo "Growing $PREFIX..."
		touch $PREFIX.input.rsp
		echo $PREFIX.key >  $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.tre >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.out >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.trl >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.sum >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.chp >> $PREFIX.input.rsp

		cat $PREFIX.input.rsp | /usr/bin/wine $EXE "$@" 2> $PREFIX.error.log  # | tee $PREFIX.fvs.log
	fi
done

# Postprocess with perl scripts
cp /usr/local/apps/growth-yield-batch/scripts/postproc/* .

echo "Postprocessing for harvest scheduler"
perl gy_live_extract.pl alt &&\
perl gy_carbon_extract.pl alt &&\
perl gy_age_extract.pl alt &&\
perl gy_cut_extract.pl alt &&\
perl gy_carbon_extract_agl.pl alt &&\
perl gy_cut_extract_cubic.pl alt


# TODO 
echo
echo "Results in temp directory $(pwd)/alt_treelists"
