#!/bin/bash
#################################################################
# Usage:
#  fvs /path/to/data
#
#  see https://github.com/Ecotrust/growth-yield-batch/wiki/FVS-directory-structure
#  for more info on how to set up data directory
#################################################################

function throw {
    #echo -e "\e[00;31mERROR :: $1\e[00m"
    echo -e "ERROR :: $1" 1>&2;
}

# 1st Arg: path to data directory 
# TODO: must contain .tre, .sum, .key, .chp  and ***.fvs files
DATADIR="$1"
if [[ -d "$DATADIR" ]]
then
    echo "Using data dir $DATADIR ..."
else
    throw "'$DATADIR' not found; please specify DATADIR"
    exit 1
fi
shift

TEMPDIR=`mktemp -d`
cp -r $DATADIR/* $TEMPDIR
cd $TEMPDIR
echo "Working in temp directory $(pwd)"

# set variant abbreviation
VARIANT=`cat *.variant`
EXE="/usr/local/apps/growth-yield-batch/fvsbin/FVS$VARIANT.exe"
if [[ -x "$EXE" ]]
then
    echo "Using $EXE..."
else
    throw "File '$EXE' is not executable or found; check the .variant file in $DATADIR"
    exit 1
fi

# process the *_original.key files and create offsets 10 offsets at 5 yr intervals
echo "Creating offset keyfiles in temp directory"
python /usr/local/apps/growth-yield-batch/scripts/preproc/CreateOffsets.py $TEMPDIR $TEMPDIR 10 5 | tee offsets.log
if [ $? -ne 0 ]; then
    throw "CreateOffsets.py failed. Check $TEMPDIR/offsets.log" 
    exit 1
fi
mkdir -p alt_treelists

# Run all the keyfiles
for f in *.key
do
	filename=$(basename "$f")
	extension="${filename##*.}"
	PREFIX="${filename%.*}"
	if [[ "$PREFIX" != *_original* ]]
	then
		echo "Growing $PREFIX..."
		touch $PREFIX.input.rsp
		echo $PREFIX.key >  $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.tre >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.out >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.trl >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.sum >> $PREFIX.input.rsp
		echo alt_treelists/$PREFIX.chp >> $PREFIX.input.rsp

		cat $PREFIX.input.rsp | /usr/bin/wine $EXE "$@" 2> $PREFIX.error.log | tee $PREFIX.fvs.log
        if [ $? -ne 0 ]; then
            throw "FVS failed" >> $PREFIX.error.log
            cat $PREFIX.error.log
            exit 1
		fi
        if [ ! -f alt_treelists/$PREFIX.out ] || [ ! -f alt_treelists/$PREFIX.trl ]; then
            throw "FVS failed to produce necessary output files" >> $PREFIX.error.log
            cat $PREFIX.error.log
            exit 1
        fi
	fi
done

# Postprocess with perl scripts
ln -s /usr/local/apps/growth-yield-batch/scripts/postproc/* .

echo "Postprocessing for harvest scheduler"
# TODO perl scripts should error out (exit 1) on failures
for f in *.pl; do
        
    echo "Running extract script $f..."
	perl $f alt > $f.log

	# Assert that alt_*.txt files exist and that they have lines
	# TODO more stringent tests
	OUT=`ls -t alt_treelists/alt_*.txt | head -n 1`
	if [[ ! -s $OUT ]]; then
        throw "$f failed. Extracted file $OUT does not exist or is invalid" | tee $f.log
        exit 1
    fi
done

echo
echo "Results in temp directory $(pwd)/alt_treelists"
